name: petshop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=1.22.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  font_awesome_flutter: ^8.8.1

  flutter_launcher_name: "^0.0.1"
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.8.1
  http: ^0.13.4
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_launcher_name:
  name: "PetShop"

flutter_native_splash:
  color: "FFC069"
  image: "assets/images/splash.png"
  fill: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
  - assets/images/